// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_Ju_hWUMlTrL_Fjx9Et43lciq1s9zrd4',
    appId: '1:78735345723:web:cf296f53fcb23af880b41e',
    messagingSenderId: '78735345723',
    projectId: 'mapapp-2367021',
    authDomain: 'mapapp-2367021.firebaseapp.com',
    storageBucket: 'mapapp-2367021.appspot.com',
    measurementId: 'G-2W0T6YLJ9D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdlk2jUG8dtcK20Q5A9zgpyOKjNhA-wTk',
    appId: '1:78735345723:android:554d250c55c2278e80b41e',
    messagingSenderId: '78735345723',
    projectId: 'mapapp-2367021',
    storageBucket: 'mapapp-2367021.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxtL7IYGvH1FsEwx8zZpgVqhu2dxHNFy8',
    appId: '1:78735345723:ios:cbdbebc7265575f980b41e',
    messagingSenderId: '78735345723',
    projectId: 'mapapp-2367021',
    storageBucket: 'mapapp-2367021.appspot.com',
    iosBundleId: 'com.example.mapApp03',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxtL7IYGvH1FsEwx8zZpgVqhu2dxHNFy8',
    appId: '1:78735345723:ios:cbdbebc7265575f980b41e',
    messagingSenderId: '78735345723',
    projectId: 'mapapp-2367021',
    storageBucket: 'mapapp-2367021.appspot.com',
    iosBundleId: 'com.example.mapApp03',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_Ju_hWUMlTrL_Fjx9Et43lciq1s9zrd4',
    appId: '1:78735345723:web:95539a39da887cc980b41e',
    messagingSenderId: '78735345723',
    projectId: 'mapapp-2367021',
    authDomain: 'mapapp-2367021.firebaseapp.com',
    storageBucket: 'mapapp-2367021.appspot.com',
    measurementId: 'G-9QLX4MG4PK',
  );
}
